-- DO NOT APPLY.
--
-- Final curator decision: no new provider identity table is needed.
--
-- Current Python sync identity is:
--   listings.user_id + listings.category_id + listing_attributes.external_id
--
-- Duplicate external_id values inside the same user/category scope are detected
-- and treated as ambiguous; the sync skips those records instead of updating
-- a random listing.
